
def DNA(string):
    code = ""
    for i in string[::-1]:
        if i == "A":
            code += "T"
        if i == "T":
            code += "A"
        if i == "C":
            code += "G"
        if i == "G":
            code += "C"
    return code


if __name__ == "__main__":
    dataset = "CTCAATTTCATCAAACCGAGTCAACGAGCCTAACGGACACATTAATCGCTGATGGCGTAGCGTAATGCGTGATTTCTACAGCTCTTGTTATTCCCCCCGGTGAAAAAACCTGGTTATCTTATAATTCGTTTATGTGGATGTGCAAAGTTACGCCGTATGTTGTAGGGCTGGAGACCTGTCGGCTACTAGATCTGTGTGTCCGCGCTACACGCCGTCCACACTACCCTCGTCCTTGGCTGGCCGGCACCTCAGGTAATTCGCATGCCCAATAAGCTTCGTGATCGCGGATTACACTCCAAGACTATGGCTGAGGGCGATGAAGCCATAATCGGTTCATGGGGATCTTTCGAGCATACCGAGAGGCTATTGTCGACGTCTAGACGCAATCCCAAGGGACGCACCTCCGGTGAAACACGTCCCTACGATAATGCTCTTAGGCGTTGACCTGTCCAACTCACGCGTATCAAGTCAAATCCACCACGACAATCCATCCTCACGAAAGATAGTTACTATCTCGCGAGGCAATGAGAGTACATTCGTTTGGCTGTCCAGAGGCTCCGTTGGCTAAGCTCTTGAGGGTCGCTCGATGTATGGCCCGGGGCGACTCCACCCGGATGAAAGAACGTCGGAGATACGCCTTAGTTCGTGCACACTGTAAGGGTACAGCCGACCTGCATAGCGTCGCAGTTCCCGTCAATCGAGTACCGGCATCAGATCGCCACGAAGTAGTCTCCTCGAAACGGAAAAACCGTTCTCCGCCTTAGTCCTTCCTGAGTCCAGACCATAACTTTGAAAGCCGTGTTGTCCTTCGTAGTCTAGTGCGTCAGATCCGCGCTTCGGCATGGAATGGCCTGATCTATACCCCCAACGCGTGTTGTTGGACGGGTTGCAACGCCA"
    string = dataset.strip()
    code = DNA(string)
    print(code)