def substring(dna_string_s, dna_string_t):
    location = []
    for i in range(len(dna_string_s)):
        if dna_string_t == dna_string_s[i: i+len(dna_string_t)]:
            location.append(i+1)
    return location

if __name__ == "__main__":
    data_set1= 'AGGTTCAAGGTACGAGACAAGGTACAAGGTATCAAGGTATAAGACAAGGTACCAAGGTATGCAAGGTACAAGGTATCAAGGTAGCAAGGTAGCAAGGTACCAAGGTACTGCCAAGGTAGCCTTCGACAAGGTACAAGGTACAAGGTACAAGGTAGCAAGGTACACAAGGTATTACAAGGTACAAGGTACTACAAGGTACCTGGCCAAGGTATCAAGGTATTCAAGGTACAAGGTATCAAGGTAGGGCAAGGTAGCAAGGTAAGGCAAGGTAGATGCAAGGTACAAGGTAGCACCAAGGTAGGACCAAGGTAACAAGGTAAGCAAGGTAAACAAGGTACAAGGTAGCAAGGTATGCAAGGTACAAGGTAACAAGGTACAAGGTAGCCACAAGGTAAATTCCCAAGGTACCAAGGTACTTACAAGGTAAGGATTAACTCAAGGTATCAAGGTACAAGGTAACACACAAGGTAAGGTAATACAAGGTACAAGGTACCAAGGTATGCCAAGGTAGCAAGGTAACAAGGTACAAGGTACAGCAAGGTATCATCCAAGGTAATCAAGGTAAGGGCCGTCAAGGTATGATTTCCAAGGTAGCAAGGTACAGTCAAGGTATCAAGGTAGGCTGCAAGGTACAAGGTACAAGGTACAAGGTACATGGCACCAAGGTAGTCCCATCAAGGTAGTACACAAGGTACATCAAGGTAAATTGTTCTGTGCAAGGTAGATGGGCAAGGTACCAAGGTACAAGGTATCCAAGGTAGTCAAGGTACAAGGTACAAGGTAGCACAAGGTACAAGGTACAAGGTATCCCAAGGTACAAGGTAACAAGGTAGCAAGGTATCAAGGTACAAGGTAAATCTTGAGCAAGGTACAAGGTATCAGCCCAAGGTACGCCACCAAGGTATCAAGGTA'
    data_set2= "CAAGGTACA"
    dna_string_s = data_set1.strip()
    dna_string_t = data_set2.strip()
    location = substring(dna_string_s, dna_string_t)
    for i in location:
        print(i, end=" ")